<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <OutputType>Exe</OutputType>
        <RootNamespace>BepInExLogAnalysis.Test</RootNamespace>
        <TargetFramework>net10.0</TargetFramework>
        <TestingPlatformDotnetTestSupport>true</TestingPlatformDotnetTestSupport>
        <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
    </PropertyGroup>

    <ItemGroup>
        <Content Include="xunit.runner.json" CopyToOutputDirectory="PreserveNewest" />
    </ItemGroup>
    
    <ItemGroup>
       <EmbeddedResource Include="LogFiles/*" LogicalName="test_logs/%(Filename)" /> 
    </ItemGroup>

    <ItemGroup>
        <Using Include="Xunit" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="xunit.v3.mtp-v2" Version="3.2.2" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="../BepInExLogAnalysis/BepInExLogAnalysis.csproj" />
    </ItemGroup>

</Project>